### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by arctic-hen7** [dobefore/cross-compile-openssl-musl#1]
Hey! I'd like to use this in one of my projects to support musl cross-compilation, but I'd just like to be clear about what the project license is. Would you mind adding a `LICENSE` file to the root so people can see how they're allowed to use this code more easily?

**Comment by dobefore** [comment]
hello @arctic-hen7 ,I am willing to share this with everyone. 

As for the license ,I don;'t know whichever I should choose,becuase I use musl toolchains from the site musl.cc.

I will appreciate it if you could  give me some advice !

**Comment by arctic-hen7** [comment]
The license is just for the code you've written, so the MIT license should be fine (it's what I use for most of my projects, at least).

**Comment by dobefore** [comment]
Thanks for your suggestion, i'll take it and I will add license ASAP.

**Comment by arctic-hen7** [comment]
Much appreciated!
